# Generated by Django 3.2.4 on 2021-06-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('categoria', models.IntegerField(choices=[(0, 'Categoria'), (1, 'Bebidas'), (3, 'Varios'), (2, 'Comestibles')], default=0)),
                ('descripcion', models.TextField(max_length=30)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
