# Generated by Django 3.2.4 on 2021-06-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRUEBAFINAL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[(3, 'Varios'), (2, 'Comestibles'), (1, 'Bebidas'), (0, 'Categoria')], default=0),
        ),
    ]
