# Generated by Django 3.2.4 on 2021-06-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRUEBAFINAL', '0003_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[(3, 'Varios'), (1, 'Bebidas'), (0, 'Categoria'), (2, 'Comestibles')], default=0),
        ),
    ]
