# Generated by Django 3.2.4 on 2021-06-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRUEBAFINAL', '0005_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[(2, 'Comestibles'), (3, 'Varios'), (1, 'Bebidas'), (0, 'Categoria')], default=0),
        ),
    ]
