# Generated by Django 3.2.4 on 2021-06-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRUEBAFINAL', '0013_auto_20210622_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[(2, 'Comestibles'), (3, 'Varios'), (0, 'Categoria'), (1, 'Bebidas')], default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
    ]
