# Generated by Django 3.2.4 on 2021-06-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRUEBAFINAL', '0014_auto_20210623_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Bebidas'), (3, 'Varios'), (2, 'Comestibles'), (0, 'Categoria')], default=0),
        ),
    ]
