# Generated by Django 3.2.4 on 2021-07-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRUEBAFINAL', '0018_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[(2, 'Comestibles'), (0, 'Categoria'), (1, 'Bebidas'), (3, 'Varios')], default=0),
        ),
    ]
