# Generated by Django 3.2.4 on 2021-07-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRUEBAFINAL', '0019_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[(0, 'Categoria'), (3, 'Varios'), (1, 'Bebidas'), (2, 'Comestibles')], default=0),
        ),
    ]
