# Generated by Django 3.2.4 on 2021-07-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRUEBAFINAL', '0020_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[(0, 'Categoria'), (3, 'Varios'), (2, 'Comestibles'), (1, 'Bebidas')], default=0),
        ),
    ]
