# Generated by Django 3.2.4 on 2021-07-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRUEBAFINAL', '0024_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[(3, 'Varios'), (2, 'Comestibles'), (0, 'Categoria'), (1, 'Bebidas')], default=0),
        ),
    ]
