# Generated by Django 3.2.4 on 2021-07-07 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PRUEBAFINAL', '0027_alter_categoria_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PRUEBAFINAL.categoria', verbose_name='Category'),
        ),
    ]
