# Generated by Django 3.2.4 on 2021-07-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRUEBAFINAL', '0028_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='codigo',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Bebidas'), (2, 'Comestibles'), (3, 'Varios'), (0, 'Categoria')], default=0),
        ),
    ]
