# Generated by Django 3.2.4 on 2021-07-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRUEBAFINAL', '0030_auto_20210707_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[(3, 'Varios'), (1, 'Bebidas'), (2, 'Comestibles'), (0, 'Categoria')], default=0),
        ),
    ]
