# Generated by Django 3.2.4 on 2021-07-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PRUEBAFINAL', '0031_alter_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Bebidas'), (2, 'Comestibles'), (0, 'Categoria'), (3, 'Varios')], default=0),
        ),
    ]
