# Generated by Django 3.2.4 on 2021-07-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRUEBAFINAL', '0033_auto_20210707_0458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='codigo',
        ),
    ]
